# 创建一个股灾node上的文件到pod中去

apiVersion: v1
kind: Pod
metadata:
  name: visa-pod
  namespace: visa-expirements
spec:
  # restartPolicy: Never
  # nodeSelector:
    # key: k8s-node1
  hostNetwork: true
  containers:
  - image: vanguo996/centos-pyvisa:websockets-server-entrypoint
    name: visa-server
    volumeMounts:
      - name: dkms-src
        mountPath: /usr/src
      - name: dkms-lib  
        mountPath: /var/lib/dkms 
      - name: lib-modules
        mountPath: /lib/modules
    securityContext:
      privileged: true
    ports:
      - containerPort: 8765
  volumes:
    - name: dkms-src
      hostPath:
        path: /usr/src
    - name: dkms-lib
      hostPath:
        path: /var/lib/dkms
    - name: lib-modules
      hostPath: 
        path: /lib/modules
