apiVersion: v1
kind: Pod
metadata:
  name: no-visa-pod
  namespace: visa-expirements
spec:
  # hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - image: vanguo996/no-visa-test
    name: visa-server
    securityContext:
      privileged: true

