apiVersion: v1
kind: Service
metadata:
  name: demo-react-nodeport
  namespace: visa-expirements
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30123
  selector:
    app: demo-react